spring:
  application:
    name: NovaRideLocationService
server:
  port: 7477

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    preferIpAddress: true



#spring.data.redis.host=localhost
#spring.data.redis.port=6379